#!/usr/bin/env python3
"""facewatch web — stdlib HTTP server: dashboard UI + JSON API.

Read-only over the LAN; mutating endpoints (enroll / promote / forget) are
accepted from localhost only — the `facewatch` CLI is their client.
"""

import json
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse, parse_qs

from engine import EnrollRequest

MUTATING_OK = ("127.0.0.1", "::1")


def make_server(cfg, store, engine, static_dir, snaps_dir):
    class Handler(BaseHTTPRequestHandler):
        server_version = "facewatch"

        # ------------------------------------------------------------- plumbing
        def log_message(self, fmt, *args):
            pass  # journald noise control; errors still surface via tracebacks

        def _send(self, code, body, ctype="application/json"):
            if isinstance(body, (dict, list)):
                body = json.dumps(body).encode()
            elif isinstance(body, str):
                body = body.encode()
            self.send_response(code)
            self.send_header("Content-Type", ctype)
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(body)

        def _localhost_only(self):
            if self.client_address[0] not in MUTATING_OK:
                self._send(403, {"ok": False, "detail": "localhost only"})
                return False
            return True

        def _read_body(self):
            length = int(self.headers.get("Content-Length") or 0)
            return self.rfile.read(length) if length else b""

        # ---------------------------------------------------------------- GET
        def do_GET(self):
            url = urlparse(self.path)
            if url.path == "/" or url.path == "/index.html":
                page = (static_dir / "index.html").read_bytes()
                self._send(200, page, "text/html; charset=utf-8")
            elif url.path == "/api/state":
                self._send(200, self._state())
            elif url.path == "/stream":
                self._stream()
            elif url.path.startswith("/snaps/"):
                self._snap(url.path[len("/snaps/"):])
            else:
                self._send(404, {"ok": False, "detail": "not found"})

        def _state(self):
            return {
                "now": time.time(),
                "health": engine.health(),
                "in_view": store.open_sessions(),
                "sessions": store.recent_sessions(60),
                "people": store.people_summary(),
            }

        def _stream(self):
            """MJPEG of the engine's annotated view — what the recognizer sees."""
            self.send_response(200)
            self.send_header("Cache-Control", "no-cache, private")
            self.send_header("Content-Type",
                             "multipart/x-mixed-replace; boundary=fwframe")
            self.end_headers()
            last = None
            try:
                while True:
                    jpeg = engine.get_jpeg()
                    if jpeg is not None and jpeg is not last:
                        last = jpeg
                        self.wfile.write(
                            b"--fwframe\r\nContent-Type: image/jpeg\r\n"
                            b"Content-Length: %d\r\n\r\n" % len(jpeg))
                        self.wfile.write(jpeg)
                        self.wfile.write(b"\r\n")
                    time.sleep(0.2)
            except (BrokenPipeError, ConnectionResetError, OSError):
                return

        def _snap(self, name):
            # Snapshot names are generated by us (s<id>_frame.jpg) — refuse
            # anything that could escape the snaps dir.
            if "/" in name or ".." in name or not name.endswith(".jpg"):
                self._send(404, {"ok": False, "detail": "bad name"})
                return
            path = snaps_dir / name
            if not path.is_file():
                self._send(404, {"ok": False, "detail": "no such snap"})
                return
            self._send(200, path.read_bytes(), "image/jpeg")

        # --------------------------------------------------------------- POST
        def do_POST(self):
            if not self._localhost_only():
                return
            url = urlparse(self.path)
            q = parse_qs(url.query)
            if url.path == "/api/enroll":
                name = (q.get("name") or [""])[0].strip()
                shots = int((q.get("shots") or ["5"])[0])
                if not name:
                    self._send(400, {"ok": False, "detail": "name required"})
                    return
                res = engine.submit(EnrollRequest("camera", name, shots=shots),
                                    timeout=shots * 2 + 20)
                self._send(200 if res["ok"] else 422, res)
            elif url.path == "/api/enroll_file":
                name = (q.get("name") or [""])[0].strip()
                body = self._read_body()
                if not name or not body:
                    self._send(400, {"ok": False,
                                     "detail": "name query param + image body required"})
                    return
                res = engine.submit(EnrollRequest("file", name, image_bytes=body))
                self._send(200 if res["ok"] else 422, res)
            elif url.path == "/api/promote":
                try:
                    payload = json.loads(self._read_body() or b"{}")
                    pid = store.promote(int(payload["session_id"]), payload["name"])
                    engine.reload_embeddings_flag.set()
                    self._send(200, {"ok": True,
                                     "detail": "promoted to person %d" % pid})
                except (KeyError, ValueError, json.JSONDecodeError) as exc:
                    self._send(422, {"ok": False, "detail": str(exc)})
            elif url.path == "/api/forget":
                try:
                    payload = json.loads(self._read_body() or b"{}")
                    ok = store.forget(payload["name"])
                    engine.reload_embeddings_flag.set()
                    self._send(200 if ok else 404,
                               {"ok": ok,
                                "detail": "forgotten" if ok else "no such person"})
                except (KeyError, json.JSONDecodeError) as exc:
                    self._send(422, {"ok": False, "detail": str(exc)})
            else:
                self._send(404, {"ok": False, "detail": "not found"})

    return ThreadingHTTPServer(("0.0.0.0", cfg["web"]["port"]), Handler)
